/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module derelict.opengl3.ext;

private
{
    import derelict.opengl3.types;
    import derelict.opengl3.constants;
    import derelict.opengl3.internal;
}

enum : uint
{
    // GL_EXT_texture_filter_anisotropic
    GL_TEXTURE_MAX_ANISOTROPY_EXT       = 0x84FE,
    GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT   = 0x84FF,

    // GL_EXT_framebuffer_object
    GL_INVALID_FRAMEBUFFER_OPERATION_EXT = 0x0506,
    GL_MAX_RENDERBUFFER_SIZE_EXT        = 0x84E8,
    GL_FRAMEBUFFER_BINDING_EXT          = 0x8CA6,
    GL_RENDERBUFFER_BINDING_EXT         = 0x8CA7,
    GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_EXT = 0x8CD0,
    GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_EXT = 0x8CD1,
    GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_EXT = 0x8CD2,
    GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_EXT = 0x8CD3,
    GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_3D_ZOFFSET_EXT = 0x8CD4,
    GL_FRAMEBUFFER_COMPLETE_EXT         = 0x8CD5,
    GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT = 0x8CD6,
    GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_EXT = 0x8CD7,
    GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT = 0x8CD9,
    GL_FRAMEBUFFER_INCOMPLETE_FORMATS_EXT = 0x8CDA,
    GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_EXT = 0x8CDB,
    GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER_EXT = 0x8CDC,
    GL_FRAMEBUFFER_UNSUPPORTED_EXT      = 0x8CDD,
    GL_MAX_COLOR_ATTACHMENTS_EXT        = 0x8CDF,
    GL_COLOR_ATTACHMENT0_EXT            = 0x8CE0,
    GL_COLOR_ATTACHMENT1_EXT            = 0x8CE1,
    GL_COLOR_ATTACHMENT2_EXT            = 0x8CE2,
    GL_COLOR_ATTACHMENT3_EXT            = 0x8CE3,
    GL_COLOR_ATTACHMENT4_EXT            = 0x8CE4,
    GL_COLOR_ATTACHMENT5_EXT            = 0x8CE5,
    GL_COLOR_ATTACHMENT6_EXT            = 0x8CE6,
    GL_COLOR_ATTACHMENT7_EXT            = 0x8CE7,
    GL_COLOR_ATTACHMENT8_EXT            = 0x8CE8,
    GL_COLOR_ATTACHMENT9_EXT            = 0x8CE9,
    GL_COLOR_ATTACHMENT10_EXT           = 0x8CEA,
    GL_COLOR_ATTACHMENT11_EXT           = 0x8CEB,
    GL_COLOR_ATTACHMENT12_EXT           = 0x8CEC,
    GL_COLOR_ATTACHMENT13_EXT           = 0x8CED,
    GL_COLOR_ATTACHMENT14_EXT           = 0x8CEE,
    GL_COLOR_ATTACHMENT15_EXT           = 0x8CEF,
    GL_DEPTH_ATTACHMENT_EXT             = 0x8D00,
    GL_STENCIL_ATTACHMENT_EXT           = 0x8D20,
    GL_FRAMEBUFFER_EXT                  = 0x8D40,
    GL_RENDERBUFFER_EXT                 = 0x8D41,
    GL_RENDERBUFFER_WIDTH_EXT           = 0x8D42,
    GL_RENDERBUFFER_HEIGHT_EXT          = 0x8D43,
    GL_RENDERBUFFER_INTERNAL_FORMAT_EXT = 0x8D44,
    GL_STENCIL_INDEX1_EXT               = 0x8D46,
    GL_STENCIL_INDEX4_EXT               = 0x8D47,
    GL_STENCIL_INDEX8_EXT               = 0x8D48,
    GL_STENCIL_INDEX16_EXT              = 0x8D49,
    GL_RENDERBUFFER_RED_SIZE_EXT        = 0x8D50,
    GL_RENDERBUFFER_GREEN_SIZE_EXT      = 0x8D51,
    GL_RENDERBUFFER_BLUE_SIZE_EXT       = 0x8D52,
    GL_RENDERBUFFER_ALPHA_SIZE_EXT      = 0x8D53,
    GL_RENDERBUFFER_DEPTH_SIZE_EXT      = 0x8D54,
    GL_RENDERBUFFER_STENCIL_SIZE_EXT    = 0x8D55,
    
    // GL_EXT_direct_state_access
    GL_PROGRAM_MATRIX_EXT               = 0x8E2D,
    GL_TRANSPOSE_PROGRAM_MATRIX_EXT     = 0x8E2E,
    GL_PROGRAM_MATRIX_STACK_DEPTH_EXT   = 0x8E2F,
}

// GL_EXT_texture_filter_anisotropic
private __gshared bool _EXT_texture_filter_anisotropic;
bool EXT_texture_filter_anisotropic() @property { return _EXT_texture_filter_anisotropic; }

// GL_EXT_framebuffer_object
extern(System)
{
    alias nothrow GLboolean function(GLuint) da_glIsRenderbufferEXT;
    alias nothrow void function(GLenum, GLuint) da_glBindRenderbufferEXT;
    alias nothrow void function(GLsizei, in GLuint*) da_glDeleteRenderbuffersEXT;
    alias nothrow void function(GLsizei, GLuint*) da_glGenRenderbuffersEXT;
    alias nothrow void function(GLenum, GLenum, GLsizei, GLsizei) da_glRenderbufferStorageEXT;
    alias nothrow void function(GLenum, GLenum, GLint*) da_glGetRenderbufferParameterivEXT;
    alias nothrow GLboolean function(GLuint) da_glIsFramebufferEXT;
    alias nothrow void function(GLenum, GLuint) da_glBindFramebufferEXT;
    alias nothrow void function(GLsizei, in GLuint*) da_glDeleteFramebuffersEXT;
    alias nothrow void function(GLsizei, GLuint*) da_glGenFramebuffersEXT;
    alias nothrow GLenum function(GLenum) da_glCheckFramebufferStatusEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLuint, GLint) da_glFramebufferTexture1DEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLuint, GLint) da_glFramebufferTexture2DEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLuint, GLint, GLint) da_glFramebufferTexture3DEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLuint) da_glFramebufferRenderbufferEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLint*) da_glGetFramebufferAttachmentParameterivEXT;
    alias nothrow void function(GLenum) da_glGenerateMipmapEXT;
}

__gshared
{
    da_glIsRenderbufferEXT glIsRenderbufferEXT;
    da_glBindRenderbufferEXT glBindRenderbufferEXT;
    da_glDeleteRenderbuffersEXT glDeleteRenderbuffersEXT;
    da_glGenRenderbuffersEXT glGenRenderbuffersEXT;
    da_glRenderbufferStorageEXT glRenderbufferStorageEXT;
    da_glGetRenderbufferParameterivEXT glGetRenderbufferParameterivEXT;
    da_glIsFramebufferEXT glIsFramebufferEXT;
    da_glBindFramebufferEXT glBindFramebufferEXT;
    da_glDeleteFramebuffersEXT glDeleteFramebuffersEXT;
    da_glGenFramebuffersEXT glGenFramebuffersEXT;
    da_glCheckFramebufferStatusEXT glCheckFramebufferStatusEXT;
    da_glFramebufferTexture1DEXT glFramebufferTexture1DEXT;
    da_glFramebufferTexture2DEXT glFramebufferTexture2DEXT;
    da_glFramebufferTexture3DEXT glFramebufferTexture3DEXT;
    da_glFramebufferRenderbufferEXT glFramebufferRenderbufferEXT;
    da_glGetFramebufferAttachmentParameterivEXT glGetFramebufferAttachmentParameterivEXT;
    da_glGenerateMipmapEXT glGenerateMipmapEXT;
}

// GL_EXT_direct_state_access
extern(System)
{
    alias nothrow void function(GLbitfield) da_glClientAttribDefaultEXT;
    alias nothrow void function(GLbitfield) da_glPushClientAttribDefaultEXT;
    alias nothrow void function(GLenum, const(GLfloat)*) da_glMatrixLoadfEXT;
    alias nothrow void function(GLenum, const(GLdouble)*) da_glMatrixLoaddEXT;
    alias nothrow void function(GLenum, const(GLfloat)*) da_glMatrixMultfEXT;
    alias nothrow void function(GLenum, const(GLdouble)*) da_glMatrixMultdEXT;
    alias nothrow void function(GLenum) da_glMatrixLoadIdentityEXT;
    alias nothrow void function(GLenum, GLfloat, GLfloat, GLfloat, GLfloat) da_glMatrixRotatefEXT;
    alias nothrow void function(GLenum, GLdouble, GLdouble, GLdouble, GLdouble) da_glMatrixRotatedEXT;
    alias nothrow void function(GLenum, GLfloat, GLfloat, GLfloat) da_glMatrixScalefEXT;
    alias nothrow void function(GLenum, GLdouble, GLdouble, GLdouble) da_glMatrixScaledEXT;
    alias nothrow void function(GLenum, GLfloat, GLfloat, GLfloat) da_glMatrixTranslatefEXT;
    alias nothrow void function(GLenum, GLdouble, GLdouble, GLdouble) da_glMatrixTranslatedEXT;
    alias nothrow void function(GLenum, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble) da_glMatrixFrustumEXT;
    alias nothrow void function(GLenum, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble) da_glMatrixOrthoEXT;
    alias nothrow void function(GLenum) da_glMatrixPopEXT;
    alias nothrow void function(GLenum) da_glMatrixPushEXT;
    alias nothrow void function(GLenum, const(GLfloat)*) da_glMatrixLoadTransposefEXT;
    alias nothrow void function(GLenum, const(GLdouble)*) da_glMatrixLoadTransposedEXT;
    alias nothrow void function(GLenum, const(GLfloat)*) da_glMatrixMultTransposefEXT;
    alias nothrow void function(GLenum, const(GLdouble)*) da_glMatrixMultTransposedEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLfloat) da_glTextureParameterfEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, const(GLfloat)*) da_glTextureParameterfvEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLint) da_glTextureParameteriEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, const(GLint)*) da_glTextureParameterivEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLsizei, GLint, GLenum, GLenum, const(GLvoid)*) da_glTextureImage1DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLenum, GLenum, const(GLvoid)*) da_glTextureImage2DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const(GLvoid)*) da_glTextureSubImage1DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const(GLvoid)*) da_glTextureSubImage2DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint) da_glCopyTextureImage1DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint) da_glCopyTextureImage2DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei) da_glCopyTextureSubImage1DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei) da_glCopyTextureSubImage2DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLenum, GLvoid*) da_glGetTextureImageEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLfloat*) da_glGetTextureParameterfvEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLint*) da_glGetTextureParameterivEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLfloat*) da_glGetTextureLevelParameterfvEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLint*) da_glGetTextureLevelParameterivEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const(GLvoid)*) da_glTextureImage3DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const(GLvoid)*) da_glTextureSubImage3DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei) da_glCopyTextureSubImage3DEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLfloat) da_glMultiTexParameterfEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, const(GLfloat)*) da_glMultiTexParameterfvEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLint) da_glMultiTexParameteriEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, const(GLint)*) da_glMultiTexParameterivEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLsizei, GLint, GLenum, GLenum, const(GLvoid)*) da_glMultiTexImage1DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLenum, GLenum, const(GLvoid)*) da_glMultiTexImage2DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const(GLvoid)*) da_glMultiTexSubImage1DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const(GLvoid)*) da_glMultiTexSubImage2DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint) da_glCopyMultiTexImage1DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint) da_glCopyMultiTexImage2DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLint, GLint, GLint, GLsizei) da_glCopyMultiTexSubImage1DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei) da_glCopyMultiTexSubImage2DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLenum, GLvoid*) da_glGetMultiTexImageEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLfloat*) da_glGetMultiTexParameterfvEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLint*) da_glGetMultiTexParameterivEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLfloat*) da_glGetMultiTexLevelParameterfvEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLint*) da_glGetMultiTexLevelParameterivEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const(GLvoid)*) da_glMultiTexImage3DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const(GLvoid)*) da_glMultiTexSubImage3DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei) da_glCopyMultiTexSubImage3DEXT;
    alias nothrow void function(GLenum, GLenum, GLuint) da_glBindMultiTextureEXT;
    alias nothrow void function(GLenum, GLuint) da_glEnableClientStateIndexedEXT;
    alias nothrow void function(GLenum, GLuint) da_glDisableClientStateIndexedEXT;
    alias nothrow void function(GLenum, GLint, GLenum, GLsizei, const(GLvoid)*) da_glMultiTexCoordPointerEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLfloat) da_glMultiTexEnvfEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, const(GLfloat)*) da_glMultiTexEnvfvEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLint) da_glMultiTexEnviEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, const(GLint)*) da_glMultiTexEnvivEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLdouble) da_glMultiTexGendEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, const(GLdouble)*) da_glMultiTexGendvEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLfloat) da_glMultiTexGenfEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, const(GLfloat)*) da_glMultiTexGenfvEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLint) da_glMultiTexGeniEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, const(GLint)*) da_glMultiTexGenivEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLfloat*) da_glGetMultiTexEnvfvEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLint*) da_glGetMultiTexEnvivEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLdouble*) da_glGetMultiTexGendvEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLfloat*) da_glGetMultiTexGenfvEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLint*) da_glGetMultiTexGenivEXT;
    alias nothrow void function(GLenum, GLuint, GLfloat*) da_glGetFloatIndexedvEXT;
    alias nothrow void function(GLenum, GLuint, GLdouble*) da_glGetDoubleIndexedvEXT;
    alias nothrow void function(GLenum, GLuint, GLvoid* *data) da_glGetPointerIndexedvEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const(GLvoid)*) da_glCompressedTextureImage3DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const(GLvoid)*) da_glCompressedTextureImage2DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const(GLvoid)*) da_glCompressedTextureImage1DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const(GLvoid)*) da_glCompressedTextureSubImage3DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const(GLvoid)*) da_glCompressedTextureSubImage2DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const(GLvoid)*) da_glCompressedTextureSubImage1DEXT;
    alias nothrow void function(GLuint, GLenum, GLint, GLvoid*) da_glGetCompressedTextureImageEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const(GLvoid)*) da_glCompressedMultiTexImage3DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const(GLvoid)*) da_glCompressedMultiTexImage2DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const(GLvoid)*) da_glCompressedMultiTexImage1DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const(GLvoid)*) da_glCompressedMultiTexSubImage3DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const(GLvoid)*) da_glCompressedMultiTexSubImage2DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const(GLvoid)*) da_glCompressedMultiTexSubImage1DEXT;
    alias nothrow void function(GLenum, GLenum, GLint, GLvoid*) da_glGetCompressedMultiTexImageEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLsizei, const(GLvoid)*) da_glNamedProgramStringEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLdouble, GLdouble, GLdouble, GLdouble) da_glNamedProgramLocalParameter4dEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, const(GLdouble)*) da_glNamedProgramLocalParameter4dvEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLfloat, GLfloat, GLfloat, GLfloat) da_glNamedProgramLocalParameter4fEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, const(GLfloat)*) da_glNamedProgramLocalParameter4fvEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLdouble*) da_glGetNamedProgramLocalParameterdvEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLfloat*) da_glGetNamedProgramLocalParameterfvEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLint*) da_glGetNamedProgramivEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLvoid*) da_glGetNamedProgramStringEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLsizei, const(GLfloat)*) da_glNamedProgramLocalParameters4fvEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLint, GLint, GLint, GLint) da_glNamedProgramLocalParameterI4iEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, const(GLint)*) da_glNamedProgramLocalParameterI4ivEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLsizei, const(GLint)*) da_glNamedProgramLocalParametersI4ivEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLuint, GLuint, GLuint, GLuint) da_glNamedProgramLocalParameterI4uiEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, const(GLuint)*) da_glNamedProgramLocalParameterI4uivEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLsizei, const(GLuint)*) da_glNamedProgramLocalParametersI4uivEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLint*) da_glGetNamedProgramLocalParameterIivEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLuint*) da_glGetNamedProgramLocalParameterIuivEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, const(GLint)*) da_glTextureParameterIivEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, const(GLuint)*) da_glTextureParameterIuivEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLint*) da_glGetTextureParameterIivEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLuint*) da_glGetTextureParameterIuivEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, const(GLint)*) da_glMultiTexParameterIivEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, const(GLuint)*) da_glMultiTexParameterIuivEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLint*) da_glGetMultiTexParameterIivEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLuint*) da_glGetMultiTexParameterIuivEXT;
    alias nothrow void function(GLuint, GLint, GLfloat) da_glProgramUniform1fEXT;
    alias nothrow void function(GLuint, GLint, GLfloat, GLfloat) da_glProgramUniform2fEXT;
    alias nothrow void function(GLuint, GLint, GLfloat, GLfloat, GLfloat) da_glProgramUniform3fEXT;
    alias nothrow void function(GLuint, GLint, GLfloat, GLfloat, GLfloat, GLfloat) da_glProgramUniform4fEXT;
    alias nothrow void function(GLuint, GLint, GLint) da_glProgramUniform1iEXT;
    alias nothrow void function(GLuint, GLint, GLint, GLint) da_glProgramUniform2iEXT;
    alias nothrow void function(GLuint, GLint, GLint, GLint, GLint) da_glProgramUniform3iEXT;
    alias nothrow void function(GLuint, GLint, GLint, GLint, GLint, GLint) da_glProgramUniform4iEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLfloat)*) da_glProgramUniform1fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLfloat)*) da_glProgramUniform2fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLfloat)*) da_glProgramUniform3fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLfloat)*) da_glProgramUniform4fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLint)*) da_glProgramUniform1ivEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLint)*) da_glProgramUniform2ivEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLint)*) da_glProgramUniform3ivEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLint)*) da_glProgramUniform4ivEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLfloat)*) da_glProgramUniformMatrix2fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLfloat)*) da_glProgramUniformMatrix3fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLfloat)*) da_glProgramUniformMatrix4fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLfloat)*) da_glProgramUniformMatrix2x3fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLfloat)*) da_glProgramUniformMatrix3x2fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLfloat)*) da_glProgramUniformMatrix2x4fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLfloat)*) da_glProgramUniformMatrix4x2fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLfloat)*) da_glProgramUniformMatrix3x4fvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLfloat)*) da_glProgramUniformMatrix4x3fvEXT;
    alias nothrow void function(GLuint, GLint, GLuint) da_glProgramUniform1uiEXT;
    alias nothrow void function(GLuint, GLint, GLuint, GLuint) da_glProgramUniform2uiEXT;
    alias nothrow void function(GLuint, GLint, GLuint, GLuint, GLuint) da_glProgramUniform3uiEXT;
    alias nothrow void function(GLuint, GLint, GLuint, GLuint, GLuint, GLuint) da_glProgramUniform4uiEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLuint)*) da_glProgramUniform1uivEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLuint)*) da_glProgramUniform2uivEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLuint)*) da_glProgramUniform3uivEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLuint)*) da_glProgramUniform4uivEXT;
    alias nothrow void function(GLuint, GLsizeiptr, const(GLvoid)*, GLenum) da_glNamedBufferDataEXT;
    alias nothrow void function(GLuint, GLintptr, GLsizeiptr, const(GLvoid)*) da_glNamedBufferSubDataEXT;
    alias nothrow GLvoid* function(GLuint, GLenum) da_glMapNamedBufferEXT;
    alias nothrow GLboolean function(GLuint) da_glUnmapNamedBufferEXT;
    alias nothrow GLvoid* function(GLuint, GLintptr, GLsizeiptr, GLbitfield) da_glMapNamedBufferRangeEXT;
    alias nothrow void function(GLuint, GLintptr, GLsizeiptr) da_glFlushMappedNamedBufferRangeEXT;
    alias nothrow void function(GLuint, GLuint, GLintptr, GLintptr, GLsizeiptr) da_glNamedCopyBufferSubDataEXT;
    alias nothrow void function(GLuint, GLenum, GLint*) da_glGetNamedBufferParameterivEXT;
    alias nothrow void function(GLuint, GLenum, GLvoid* *params) da_glGetNamedBufferPointervEXT;
    alias nothrow void function(GLuint, GLintptr, GLsizeiptr, GLvoid*) da_glGetNamedBufferSubDataEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLuint) da_glTextureBufferEXT;
    alias nothrow void function(GLenum, GLenum, GLenum, GLuint) da_glMultiTexBufferEXT;
    alias nothrow void function(GLuint, GLenum, GLsizei, GLsizei) da_glNamedRenderbufferStorageEXT;
    alias nothrow void function(GLuint, GLenum, GLint*) da_glGetNamedRenderbufferParameterivEXT;
    alias nothrow GLenum function(GLuint, GLenum) da_glCheckNamedFramebufferStatusEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLuint, GLint) da_glNamedFramebufferTexture1DEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLuint, GLint) da_glNamedFramebufferTexture2DEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLuint, GLint, GLint) da_glNamedFramebufferTexture3DEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLuint) da_glNamedFramebufferRenderbufferEXT;
    alias nothrow void function(GLuint, GLenum, GLenum, GLint*) da_glGetNamedFramebufferAttachmentParameterivEXT;
    alias nothrow void function(GLuint, GLenum) da_glGenerateTextureMipmapEXT;
    alias nothrow void function(GLenum, GLenum) da_glGenerateMultiTexMipmapEXT;
    alias nothrow void function(GLuint, GLenum) da_glFramebufferDrawBufferEXT;
    alias nothrow void function(GLuint, GLsizei, const(GLenum)*) da_glFramebufferDrawBuffersEXT;
    alias nothrow void function(GLuint, GLenum) da_glFramebufferReadBufferEXT;
    alias nothrow void function(GLuint, GLenum, GLint*) da_glGetFramebufferParameterivEXT;
    alias nothrow void function(GLuint, GLsizei, GLenum, GLsizei, GLsizei) da_glNamedRenderbufferStorageMultisampleEXT;
    alias nothrow void function(GLuint, GLsizei, GLsizei, GLenum, GLsizei, GLsizei) da_glNamedRenderbufferStorageMultisampleCoverageEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLint) da_glNamedFramebufferTextureEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLint, GLint) da_glNamedFramebufferTextureLayerEXT;
    alias nothrow void function(GLuint, GLenum, GLuint, GLint, GLenum) da_glNamedFramebufferTextureFaceEXT;
    alias nothrow void function(GLuint, GLenum, GLuint) da_glTextureRenderbufferEXT;
    alias nothrow void function(GLenum, GLenum, GLuint) da_glMultiTexRenderbufferEXT;
    alias nothrow void function(GLuint, GLint, GLdouble) da_glProgramUniform1dEXT;
    alias nothrow void function(GLuint, GLint, GLdouble, GLdouble) da_glProgramUniform2dEXT;
    alias nothrow void function(GLuint, GLint, GLdouble, GLdouble, GLdouble) da_glProgramUniform3dEXT;
    alias nothrow void function(GLuint, GLint, GLdouble, GLdouble, GLdouble, GLdouble) da_glProgramUniform4dEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLdouble)*) da_glProgramUniform1dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLdouble)*) da_glProgramUniform2dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLdouble)*) da_glProgramUniform3dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, const(GLdouble)*) da_glProgramUniform4dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLdouble)*) da_glProgramUniformMatrix2dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLdouble)*) da_glProgramUniformMatrix3dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLdouble)*) da_glProgramUniformMatrix4dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLdouble)*) da_glProgramUniformMatrix2x3dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLdouble)*) da_glProgramUniformMatrix2x4dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLdouble)*) da_glProgramUniformMatrix3x2dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLdouble)*) da_glProgramUniformMatrix3x4dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLdouble)*) da_glProgramUniformMatrix4x2dvEXT;
    alias nothrow void function(GLuint, GLint, GLsizei, GLboolean, const(GLdouble)*) da_glProgramUniformMatrix4x3dvEXT;
    alias nothrow void function(GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr) da_glVertexArrayVertexOffsetEXT;
    alias nothrow void function(GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr) da_glVertexArrayColorOffsetEXT;
    alias nothrow void function(GLuint, GLuint, GLsizei, GLintptr) da_glVertexArrayEdgeFlagOffsetEXT;
    alias nothrow void function(GLuint, GLuint, GLenum, GLsizei, GLintptr) da_glVertexArrayIndexOffsetEXT;
    alias nothrow void function(GLuint, GLuint, GLenum, GLsizei, GLintptr) da_glVertexArrayNormalOffsetEXT;
    alias nothrow void function(GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr) da_glVertexArrayTexCoordOffsetEXT;
    alias nothrow void function(GLuint, GLuint, GLenum, GLint, GLenum, GLsizei, GLintptr) da_glVertexArrayMultiTexCoordOffsetEXT;
    alias nothrow void function(GLuint, GLuint, GLenum, GLsizei, GLintptr) da_glVertexArrayFogCoordOffsetEXT;
    alias nothrow void function(GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr) da_glVertexArraySecondaryColorOffsetEXT;
    alias nothrow void function(GLuint, GLuint, GLuint, GLint, GLenum, GLboolean normalized, GLsizei, GLintptr) da_glVertexArrayVertexAttribOffsetEXT;
    alias nothrow void function(GLuint, GLuint, GLuint, GLint, GLenum, GLsizei, GLintptr) da_glVertexArrayVertexAttribIOffsetEXT;
    alias nothrow void function(GLuint, GLenum) da_glEnableVertexArrayEXT;
    alias nothrow void function(GLuint, GLenum) da_glDisableVertexArrayEXT;
    alias nothrow void function(GLuint, GLuint) da_glEnableVertexArrayAttribEXT;
    alias nothrow void function(GLuint, GLuint) da_glDisableVertexArrayAttribEXT;
    alias nothrow void function(GLuint, GLenum, GLint*) da_glGetVertexArrayIntegervEXT;
    alias nothrow void function(GLuint, GLenum, GLvoid**) da_glGetVertexArrayPointervEXT;
    alias nothrow void function(GLuint, GLuint, GLenum, GLint*) da_glGetVertexArrayIntegeri_vEXT;
    alias nothrow void function(GLuint, GLuint, GLenum, GLvoid**) da_glGetVertexArrayPointeri_vEXT;
    alias nothrow void function(GLenum, GLuint) da_glEnableClientStateiEXT;
    alias nothrow void function(GLenum, GLuint) da_glDisableClientStateiEXT;
    alias nothrow void function(GLenum, GLuint, GLfloat*) da_glGetFloati_vEXT;
    alias nothrow void function(GLenum, GLuint, GLdouble*) da_glGetDoublei_vEXT;
    alias nothrow void function(GLenum, GLuint, GLvoid**) da_glGetPointeri_vEXT;
    alias nothrow void function(GLenum cap, GLuint index) da_glEnableIndexedEXT;
    alias nothrow void function(GLenum cap, GLuint index) da_glDisableIndexedEXT;
    alias nothrow GLboolean function(GLenum target, GLuint index) da_glIsEnabledIndexedEXT;
    alias nothrow void function(GLenum target, GLuint index, GLint *params) da_glGetIntegerIndexedvEXT;
    alias nothrow void function(GLenum target, GLuint index, GLboolean *params) da_glGetBooleanIndexedvEXT;
}

__gshared
{
    da_glClientAttribDefaultEXT glClientAttribDefaultEXT;
    da_glPushClientAttribDefaultEXT glPushClientAttribDefaultEXT;
    da_glMatrixLoadfEXT glMatrixLoadfEXT;
    da_glMatrixLoaddEXT glMatrixLoaddEXT;
    da_glMatrixMultfEXT glMatrixMultfEXT;
    da_glMatrixMultdEXT glMatrixMultdEXT;
    da_glMatrixLoadIdentityEXT glMatrixLoadIdentityEXT;
    da_glMatrixRotatefEXT glMatrixRotatefEXT;
    da_glMatrixRotatedEXT glMatrixRotatedEXT;
    da_glMatrixScalefEXT glMatrixScalefEXT;
    da_glMatrixScaledEXT glMatrixScaledEXT;
    da_glMatrixTranslatefEXT glMatrixTranslatefEXT;
    da_glMatrixTranslatedEXT glMatrixTranslatedEXT;
    da_glMatrixFrustumEXT glMatrixFrustumEXT;
    da_glMatrixOrthoEXT glMatrixOrthoEXT;
    da_glMatrixPopEXT glMatrixPopEXT;
    da_glMatrixPushEXT glMatrixPushEXT;
    da_glMatrixLoadTransposefEXT glMatrixLoadTransposefEXT;
    da_glMatrixLoadTransposedEXT glMatrixLoadTransposedEXT;
    da_glMatrixMultTransposefEXT glMatrixMultTransposefEXT;
    da_glMatrixMultTransposedEXT glMatrixMultTransposedEXT;
    da_glTextureParameterfEXT glTextureParameterfEXT;
    da_glTextureParameterfvEXT glTextureParameterfvEXT;
    da_glTextureParameteriEXT glTextureParameteriEXT;
    da_glTextureParameterivEXT glTextureParameterivEXT;
    da_glTextureImage1DEXT glTextureImage1DEXT;
    da_glTextureImage2DEXT glTextureImage2DEXT;
    da_glTextureSubImage1DEXT glTextureSubImage1DEXT;
    da_glTextureSubImage2DEXT glTextureSubImage2DEXT;
    da_glCopyTextureImage1DEXT glCopyTextureImage1DEXT;
    da_glCopyTextureImage2DEXT glCopyTextureImage2DEXT;
    da_glCopyTextureSubImage1DEXT glCopyTextureSubImage1DEXT;
    da_glCopyTextureSubImage2DEXT glCopyTextureSubImage2DEXT;
    da_glGetTextureImageEXT glGetTextureImageEXT;
    da_glGetTextureParameterfvEXT glGetTextureParameterfvEXT;
    da_glGetTextureParameterivEXT glGetTextureParameterivEXT;
    da_glGetTextureLevelParameterfvEXT glGetTextureLevelParameterfvEXT;
    da_glGetTextureLevelParameterivEXT glGetTextureLevelParameterivEXT;
    da_glTextureImage3DEXT glTextureImage3DEXT;
    da_glTextureSubImage3DEXT glTextureSubImage3DEXT;
    da_glCopyTextureSubImage3DEXT glCopyTextureSubImage3DEXT;
    da_glMultiTexParameterfEXT glMultiTexParameterfEXT;
    da_glMultiTexParameterfvEXT glMultiTexParameterfvEXT;
    da_glMultiTexParameteriEXT glMultiTexParameteriEXT;
    da_glMultiTexParameterivEXT glMultiTexParameterivEXT;
    da_glMultiTexImage1DEXT glMultiTexImage1DEXT;
    da_glMultiTexImage2DEXT glMultiTexImage2DEXT;
    da_glMultiTexSubImage1DEXT glMultiTexSubImage1DEXT;
    da_glMultiTexSubImage2DEXT glMultiTexSubImage2DEXT;
    da_glCopyMultiTexImage1DEXT glCopyMultiTexImage1DEXT;
    da_glCopyMultiTexImage2DEXT glCopyMultiTexImage2DEXT;
    da_glCopyMultiTexSubImage1DEXT glCopyMultiTexSubImage1DEXT;
    da_glCopyMultiTexSubImage2DEXT glCopyMultiTexSubImage2DEXT;
    da_glGetMultiTexImageEXT glGetMultiTexImageEXT;
    da_glGetMultiTexParameterfvEXT glGetMultiTexParameterfvEXT;
    da_glGetMultiTexParameterivEXT glGetMultiTexParameterivEXT;
    da_glGetMultiTexLevelParameterfvEXT glGetMultiTexLevelParameterfvEXT;
    da_glGetMultiTexLevelParameterivEXT glGetMultiTexLevelParameterivEXT;
    da_glMultiTexImage3DEXT glMultiTexImage3DEXT;
    da_glMultiTexSubImage3DEXT glMultiTexSubImage3DEXT;
    da_glCopyMultiTexSubImage3DEXT glCopyMultiTexSubImage3DEXT;
    da_glBindMultiTextureEXT glBindMultiTextureEXT;
    da_glEnableClientStateIndexedEXT glEnableClientStateIndexedEXT;
    da_glDisableClientStateIndexedEXT glDisableClientStateIndexedEXT;
    da_glMultiTexCoordPointerEXT glMultiTexCoordPointerEXT;
    da_glMultiTexEnvfEXT glMultiTexEnvfEXT;
    da_glMultiTexEnvfvEXT glMultiTexEnvfvEXT;
    da_glMultiTexEnviEXT glMultiTexEnviEXT;
    da_glMultiTexEnvivEXT glMultiTexEnvivEXT;
    da_glMultiTexGendEXT glMultiTexGendEXT;
    da_glMultiTexGendvEXT glMultiTexGendvEXT;
    da_glMultiTexGenfEXT glMultiTexGenfEXT;
    da_glMultiTexGenfvEXT glMultiTexGenfvEXT;
    da_glMultiTexGeniEXT glMultiTexGeniEXT;
    da_glMultiTexGenivEXT glMultiTexGenivEXT;
    da_glGetMultiTexEnvfvEXT glGetMultiTexEnvfvEXT;
    da_glGetMultiTexEnvivEXT glGetMultiTexEnvivEXT;
    da_glGetMultiTexGendvEXT glGetMultiTexGendvEXT;
    da_glGetMultiTexGenfvEXT glGetMultiTexGenfvEXT;
    da_glGetMultiTexGenivEXT glGetMultiTexGenivEXT;
    da_glGetFloatIndexedvEXT glGetFloatIndexedvEXT;
    da_glGetDoubleIndexedvEXT glGetDoubleIndexedvEXT;
    da_glGetPointerIndexedvEXT glGetPointerIndexedvEXT;
    da_glCompressedTextureImage3DEXT glCompressedTextureImage3DEXT;
    da_glCompressedTextureImage2DEXT glCompressedTextureImage2DEXT;
    da_glCompressedTextureImage1DEXT glCompressedTextureImage1DEXT;
    da_glCompressedTextureSubImage3DEXT glCompressedTextureSubImage3DEXT;
    da_glCompressedTextureSubImage2DEXT glCompressedTextureSubImage2DEXT;
    da_glCompressedTextureSubImage1DEXT glCompressedTextureSubImage1DEXT;
    da_glGetCompressedTextureImageEXT glGetCompressedTextureImageEXT;
    da_glCompressedMultiTexImage3DEXT glCompressedMultiTexImage3DEXT;
    da_glCompressedMultiTexImage2DEXT glCompressedMultiTexImage2DEXT;
    da_glCompressedMultiTexImage1DEXT glCompressedMultiTexImage1DEXT;
    da_glCompressedMultiTexSubImage3DEXT glCompressedMultiTexSubImage3DEXT;
    da_glCompressedMultiTexSubImage2DEXT glCompressedMultiTexSubImage2DEXT;
    da_glCompressedMultiTexSubImage1DEXT glCompressedMultiTexSubImage1DEXT;
    da_glGetCompressedMultiTexImageEXT glGetCompressedMultiTexImageEXT;
    da_glNamedProgramStringEXT glNamedProgramStringEXT;
    da_glNamedProgramLocalParameter4dEXT glNamedProgramLocalParameter4dEXT;
    da_glNamedProgramLocalParameter4dvEXT glNamedProgramLocalParameter4dvEXT;
    da_glNamedProgramLocalParameter4fEXT glNamedProgramLocalParameter4fEXT;
    da_glNamedProgramLocalParameter4fvEXT glNamedProgramLocalParameter4fvEXT;
    da_glGetNamedProgramLocalParameterdvEXT glGetNamedProgramLocalParameterdvEXT;
    da_glGetNamedProgramLocalParameterfvEXT glGetNamedProgramLocalParameterfvEXT;
    da_glGetNamedProgramivEXT glGetNamedProgramivEXT;
    da_glGetNamedProgramStringEXT glGetNamedProgramStringEXT;
    da_glNamedProgramLocalParameters4fvEXT glNamedProgramLocalParameters4fvEXT;
    da_glNamedProgramLocalParameterI4iEXT glNamedProgramLocalParameterI4iEXT;
    da_glNamedProgramLocalParameterI4ivEXT glNamedProgramLocalParameterI4ivEXT;
    da_glNamedProgramLocalParametersI4ivEXT glNamedProgramLocalParametersI4ivEXT;
    da_glNamedProgramLocalParameterI4uiEXT glNamedProgramLocalParameterI4uiEXT;
    da_glNamedProgramLocalParameterI4uivEXT glNamedProgramLocalParameterI4uivEXT;
    da_glNamedProgramLocalParametersI4uivEXT glNamedProgramLocalParametersI4uivEXT;
    da_glGetNamedProgramLocalParameterIivEXT glGetNamedProgramLocalParameterIivEXT;
    da_glGetNamedProgramLocalParameterIuivEXT glGetNamedProgramLocalParameterIuivEXT;
    da_glTextureParameterIivEXT glTextureParameterIivEXT;
    da_glTextureParameterIuivEXT glTextureParameterIuivEXT;
    da_glGetTextureParameterIivEXT glGetTextureParameterIivEXT;
    da_glGetTextureParameterIuivEXT glGetTextureParameterIuivEXT;
    da_glMultiTexParameterIivEXT glMultiTexParameterIivEXT;
    da_glMultiTexParameterIuivEXT glMultiTexParameterIuivEXT;
    da_glGetMultiTexParameterIivEXT glGetMultiTexParameterIivEXT;
    da_glGetMultiTexParameterIuivEXT glGetMultiTexParameterIuivEXT;
    da_glProgramUniform1fEXT glProgramUniform1fEXT;
    da_glProgramUniform2fEXT glProgramUniform2fEXT;
    da_glProgramUniform3fEXT glProgramUniform3fEXT;
    da_glProgramUniform4fEXT glProgramUniform4fEXT;
    da_glProgramUniform1iEXT glProgramUniform1iEXT;
    da_glProgramUniform2iEXT glProgramUniform2iEXT;
    da_glProgramUniform3iEXT glProgramUniform3iEXT;
    da_glProgramUniform4iEXT glProgramUniform4iEXT;
    da_glProgramUniform1fvEXT glProgramUniform1fvEXT;
    da_glProgramUniform2fvEXT glProgramUniform2fvEXT;
    da_glProgramUniform3fvEXT glProgramUniform3fvEXT;
    da_glProgramUniform4fvEXT glProgramUniform4fvEXT;
    da_glProgramUniform1ivEXT glProgramUniform1ivEXT;
    da_glProgramUniform2ivEXT glProgramUniform2ivEXT;
    da_glProgramUniform3ivEXT glProgramUniform3ivEXT;
    da_glProgramUniform4ivEXT glProgramUniform4ivEXT;
    da_glProgramUniformMatrix2fvEXT glProgramUniformMatrix2fvEXT;
    da_glProgramUniformMatrix3fvEXT glProgramUniformMatrix3fvEXT;
    da_glProgramUniformMatrix4fvEXT glProgramUniformMatrix4fvEXT;
    da_glProgramUniformMatrix2x3fvEXT glProgramUniformMatrix2x3fvEXT;
    da_glProgramUniformMatrix3x2fvEXT glProgramUniformMatrix3x2fvEXT;
    da_glProgramUniformMatrix2x4fvEXT glProgramUniformMatrix2x4fvEXT;
    da_glProgramUniformMatrix4x2fvEXT glProgramUniformMatrix4x2fvEXT;
    da_glProgramUniformMatrix3x4fvEXT glProgramUniformMatrix3x4fvEXT;
    da_glProgramUniformMatrix4x3fvEXT glProgramUniformMatrix4x3fvEXT;
    da_glProgramUniform1uiEXT glProgramUniform1uiEXT;
    da_glProgramUniform2uiEXT glProgramUniform2uiEXT;
    da_glProgramUniform3uiEXT glProgramUniform3uiEXT;
    da_glProgramUniform4uiEXT glProgramUniform4uiEXT;
    da_glProgramUniform1uivEXT glProgramUniform1uivEXT;
    da_glProgramUniform2uivEXT glProgramUniform2uivEXT;
    da_glProgramUniform3uivEXT glProgramUniform3uivEXT;
    da_glProgramUniform4uivEXT glProgramUniform4uivEXT;
    da_glNamedBufferDataEXT glNamedBufferDataEXT;
    da_glNamedBufferSubDataEXT glNamedBufferSubDataEXT;
    da_glMapNamedBufferEXT glMapNamedBufferEXT;
    da_glUnmapNamedBufferEXT glUnmapNamedBufferEXT;
    da_glMapNamedBufferRangeEXT glMapNamedBufferRangeEXT;
    da_glFlushMappedNamedBufferRangeEXT glFlushMappedNamedBufferRangeEXT;
    da_glNamedCopyBufferSubDataEXT glNamedCopyBufferSubDataEXT;
    da_glGetNamedBufferParameterivEXT glGetNamedBufferParameterivEXT;
    da_glGetNamedBufferPointervEXT glGetNamedBufferPointervEXT;
    da_glGetNamedBufferSubDataEXT glGetNamedBufferSubDataEXT;
    da_glTextureBufferEXT glTextureBufferEXT;
    da_glMultiTexBufferEXT glMultiTexBufferEXT;
    da_glNamedRenderbufferStorageEXT glNamedRenderbufferStorageEXT;
    da_glGetNamedRenderbufferParameterivEXT glGetNamedRenderbufferParameterivEXT;
    da_glCheckNamedFramebufferStatusEXT glCheckNamedFramebufferStatusEXT;
    da_glNamedFramebufferTexture1DEXT glNamedFramebufferTexture1DEXT;
    da_glNamedFramebufferTexture2DEXT glNamedFramebufferTexture2DEXT;
    da_glNamedFramebufferTexture3DEXT glNamedFramebufferTexture3DEXT;
    da_glNamedFramebufferRenderbufferEXT glNamedFramebufferRenderbufferEXT;
    da_glGetNamedFramebufferAttachmentParameterivEXT glGetNamedFramebufferAttachmentParameterivEXT;
    da_glGenerateTextureMipmapEXT glGenerateTextureMipmapEXT;
    da_glGenerateMultiTexMipmapEXT glGenerateMultiTexMipmapEXT;
    da_glFramebufferDrawBufferEXT glFramebufferDrawBufferEXT;
    da_glFramebufferDrawBuffersEXT glFramebufferDrawBuffersEXT;
    da_glFramebufferReadBufferEXT glFramebufferReadBufferEXT;
    da_glGetFramebufferParameterivEXT glGetFramebufferParameterivEXT;
    da_glNamedRenderbufferStorageMultisampleEXT glNamedRenderbufferStorageMultisampleEXT;
    da_glNamedRenderbufferStorageMultisampleCoverageEXT glNamedRenderbufferStorageMultisampleCoverageEXT;
    da_glNamedFramebufferTextureEXT glNamedFramebufferTextureEXT;
    da_glNamedFramebufferTextureLayerEXT glNamedFramebufferTextureLayerEXT;
    da_glNamedFramebufferTextureFaceEXT glNamedFramebufferTextureFaceEXT;
    da_glTextureRenderbufferEXT glTextureRenderbufferEXT;
    da_glMultiTexRenderbufferEXT glMultiTexRenderbufferEXT;
    da_glProgramUniform1dEXT glProgramUniform1dEXT;
    da_glProgramUniform2dEXT glProgramUniform2dEXT;
    da_glProgramUniform3dEXT glProgramUniform3dEXT;
    da_glProgramUniform4dEXT glProgramUniform4dEXT;
    da_glProgramUniform1dvEXT glProgramUniform1dvEXT;
    da_glProgramUniform2dvEXT glProgramUniform2dvEXT;
    da_glProgramUniform3dvEXT glProgramUniform3dvEXT;
    da_glProgramUniform4dvEXT glProgramUniform4dvEXT;
    da_glProgramUniformMatrix2dvEXT glProgramUniformMatrix2dvEXT;
    da_glProgramUniformMatrix3dvEXT glProgramUniformMatrix3dvEXT;
    da_glProgramUniformMatrix4dvEXT glProgramUniformMatrix4dvEXT;
    da_glProgramUniformMatrix2x3dvEXT glProgramUniformMatrix2x3dvEXT;
    da_glProgramUniformMatrix2x4dvEXT glProgramUniformMatrix2x4dvEXT;
    da_glProgramUniformMatrix3x2dvEXT glProgramUniformMatrix3x2dvEXT;
    da_glProgramUniformMatrix3x4dvEXT glProgramUniformMatrix3x4dvEXT;
    da_glProgramUniformMatrix4x2dvEXT glProgramUniformMatrix4x2dvEXT;
    da_glProgramUniformMatrix4x3dvEXT glProgramUniformMatrix4x3dvEXT;
    da_glVertexArrayVertexOffsetEXT glVertexArrayVertexOffsetEXT;
    da_glVertexArrayColorOffsetEXT glVertexArrayColorOffsetEXT;
    da_glVertexArrayEdgeFlagOffsetEXT glVertexArrayEdgeFlagOffsetEXT;
    da_glVertexArrayIndexOffsetEXT glVertexArrayIndexOffsetEXT;
    da_glVertexArrayNormalOffsetEXT glVertexArrayNormalOffsetEXT;
    da_glVertexArrayTexCoordOffsetEXT glVertexArrayTexCoordOffsetEXT;
    da_glVertexArrayMultiTexCoordOffsetEXT glVertexArrayMultiTexCoordOffsetEXT;
    da_glVertexArrayFogCoordOffsetEXT glVertexArrayFogCoordOffsetEXT;
    da_glVertexArraySecondaryColorOffsetEXT glVertexArraySecondaryColorOffsetEXT;
    da_glVertexArrayVertexAttribOffsetEXT glVertexArrayVertexAttribOffsetEXT;
    da_glVertexArrayVertexAttribIOffsetEXT glVertexArrayVertexAttribIOffsetEXT;
    da_glEnableVertexArrayEXT glEnableVertexArrayEXT;
    da_glDisableVertexArrayEXT glDisableVertexArrayEXT;
    da_glEnableVertexArrayAttribEXT glEnableVertexArrayAttribEXT;
    da_glDisableVertexArrayAttribEXT glDisableVertexArrayAttribEXT;
    da_glGetVertexArrayIntegervEXT glGetVertexArrayIntegervEXT;
    da_glGetVertexArrayPointervEXT glGetVertexArrayPointervEXT;
    da_glGetVertexArrayIntegeri_vEXT glGetVertexArrayIntegeri_vEXT;
    da_glGetVertexArrayPointeri_vEXT glGetVertexArrayPointeri_vEXT;
    da_glEnableClientStateiEXT glEnableClientStateiEXT;
    da_glDisableClientStateiEXT glDisableClientStateiEXT;
    da_glGetFloati_vEXT glGetFloati_vEXT;
    da_glGetDoublei_vEXT glGetDoublei_vEXT;
    da_glGetPointeri_vEXT glGetPointeri_vEXT;
    da_glEnableIndexedEXT glEnableIndexedEXT;
    da_glDisableIndexedEXT glDisableIndexedEXT;
    da_glIsEnabledIndexedEXT glIsEnabledIndexedEXT;
    da_glGetIntegerIndexedvEXT glGetIntegerIndexedvEXT;
    da_glGetBooleanIndexedvEXT glGetBooleanIndexedvEXT;
}

private __gshared bool _EXT_framebuffer_object;
bool EXT_framebuffer_object() @property { return _EXT_framebuffer_object; }
private void load_EXT_framebuffer_object()
{
    try
    {
        bindGLFunc(cast(void**)&glIsRenderbufferEXT, "glIsRenderbufferEXT");
        bindGLFunc(cast(void**)&glBindRenderbufferEXT, "glBindRenderbufferEXT");
        bindGLFunc(cast(void**)&glDeleteRenderbuffersEXT, "glDeleteRenderbuffersEXT");
        bindGLFunc(cast(void**)&glGenRenderbuffersEXT, "glGenRenderbuffersEXT");
        bindGLFunc(cast(void**)&glRenderbufferStorageEXT, "glRenderbufferStorageEXT");
        bindGLFunc(cast(void**)&glGetRenderbufferParameterivEXT, "glGetRenderbufferParameterivEXT");
        bindGLFunc(cast(void**)&glIsFramebufferEXT, "glIsFramebufferEXT");
        bindGLFunc(cast(void**)&glBindFramebufferEXT, "glBindFramebufferEXT");
        bindGLFunc(cast(void**)&glDeleteFramebuffersEXT, "glDeleteFramebuffersEXT");
        bindGLFunc(cast(void**)&glGenFramebuffersEXT, "glGenFramebuffersEXT");
        bindGLFunc(cast(void**)&glCheckFramebufferStatusEXT, "glCheckFramebufferStatusEXT");
        bindGLFunc(cast(void**)&glFramebufferTexture1DEXT, "glFramebufferTexture1DEXT");
        bindGLFunc(cast(void**)&glFramebufferTexture2DEXT, "glFramebufferTexture2DEXT");
        bindGLFunc(cast(void**)&glFramebufferTexture3DEXT, "glFramebufferTexture3DEXT");
        bindGLFunc(cast(void**)&glFramebufferRenderbufferEXT, "glFramebufferRenderbufferEXT");
        bindGLFunc(cast(void**)&glGetFramebufferAttachmentParameterivEXT, "glGetFramebufferAttachmentParameterivEXT");
        bindGLFunc(cast(void**)&glGenerateMipmapEXT, "glGenerateMipmapEXT");
        _EXT_framebuffer_object = true;
    }
    catch(Exception e)
    {
        _EXT_framebuffer_object = false;
    }
}

private __gshared bool _EXT_direct_state_access;
bool EXT_direct_state_access() @property { return _EXT_direct_state_access; }
private void load_EXT_direct_state_access(GLVersion glversion)
{
    try
    {
        if(glversion >= GLVersion.GL11)
        {
            bindGLFunc(cast(void**)&glClientAttribDefaultEXT, "glClientAttribDefaultEXT");
            bindGLFunc(cast(void**)&glPushClientAttribDefaultEXT, "glPushClientAttribDefaultEXT");
            bindGLFunc(cast(void**)&glMatrixLoadfEXT, "glMatrixLoadfEXT");
            bindGLFunc(cast(void**)&glMatrixLoaddEXT, "glMatrixLoaddEXT");
            bindGLFunc(cast(void**)&glMatrixMultfEXT, "glMatrixMultfEXT");
            bindGLFunc(cast(void**)&glMatrixMultdEXT, "glMatrixMultdEXT");
            bindGLFunc(cast(void**)&glMatrixLoadIdentityEXT, "glMatrixLoadIdentityEXT");
            bindGLFunc(cast(void**)&glMatrixRotatefEXT, "glMatrixRotatefEXT");
            bindGLFunc(cast(void**)&glMatrixRotatedEXT, "glMatrixRotatedEXT");
            bindGLFunc(cast(void**)&glMatrixScalefEXT, "glMatrixScalefEXT");
            bindGLFunc(cast(void**)&glMatrixScaledEXT, "glMatrixScaledEXT");
            bindGLFunc(cast(void**)&glMatrixTranslatefEXT, "glMatrixTranslatefEXT");
            bindGLFunc(cast(void**)&glMatrixTranslatedEXT, "glMatrixTranslatedEXT");
            bindGLFunc(cast(void**)&glMatrixOrthoEXT, "glMatrixOrthoEXT");
            bindGLFunc(cast(void**)&glMatrixFrustumEXT, "glMatrixFrustumEXT");
            bindGLFunc(cast(void**)&glMatrixPushEXT, "glMatrixPushEXT");
            bindGLFunc(cast(void**)&glMatrixPopEXT, "glMatrixPopEXT");
            bindGLFunc(cast(void**)&glTextureParameteriEXT, "glTextureParameteriEXT");
            bindGLFunc(cast(void**)&glTextureParameterivEXT, "glTextureParameterivEXT");
            bindGLFunc(cast(void**)&glTextureParameterfEXT, "glTextureParameterfEXT");
            bindGLFunc(cast(void**)&glTextureParameterfvEXT, "glTextureParameterfvEXT");
            bindGLFunc(cast(void**)&glTextureImage1DEXT, "glTextureImage1DEXT");
            bindGLFunc(cast(void**)&glTextureImage2DEXT, "glTextureImage2DEXT");
            bindGLFunc(cast(void**)&glTextureSubImage1DEXT, "glTextureSubImage1DEXT");
            bindGLFunc(cast(void**)&glTextureSubImage2DEXT, "glTextureSubImage2DEXT");
            bindGLFunc(cast(void**)&glCopyTextureImage1DEXT, "glCopyTextureImage1DEXT");
            bindGLFunc(cast(void**)&glCopyTextureImage2DEXT, "glCopyTextureImage2DEXT");
            bindGLFunc(cast(void**)&glCopyTextureSubImage1DEXT, "glCopyTextureSubImage1DEXT");
            bindGLFunc(cast(void**)&glCopyTextureSubImage2DEXT, "glCopyTextureSubImage2DEXT");
            bindGLFunc(cast(void**)&glGetTextureImageEXT, "glGetTextureImageEXT");
            bindGLFunc(cast(void**)&glGetTextureParameterfvEXT, "glGetTextureParameterfvEXT");
            bindGLFunc(cast(void**)&glGetTextureParameterivEXT, "glGetTextureParameterivEXT");
            bindGLFunc(cast(void**)&glGetTextureLevelParameterfvEXT, "glGetTextureLevelParameterfvEXT");
            bindGLFunc(cast(void**)&glGetTextureLevelParameterivEXT, "glGetTextureLevelParameterivEXT");
        }
        
        if(glversion >= GLVersion.GL12)
        {
            bindGLFunc(cast(void**)&glTextureImage3DEXT, "glTextureImage3DEXT");
            bindGLFunc(cast(void**)&glTextureSubImage3DEXT, "glTextureSubImage3DEXT");
            bindGLFunc(cast(void**)&glCopyTextureSubImage3DEXT, "glCopyTextureSubImage3DEXT");
            bindGLFunc(cast(void**)&glBindMultiTextureEXT, "glBindMultiTextureEXT");
            bindGLFunc(cast(void**)&glMultiTexCoordPointerEXT, "glMultiTexCoordPointerEXT");
            bindGLFunc(cast(void**)&glMultiTexEnvfEXT, "glMultiTexEnvfEXT");
            bindGLFunc(cast(void**)&glMultiTexEnvfvEXT, "glMultiTexEnvfvEXT");
            bindGLFunc(cast(void**)&glMultiTexEnviEXT, "glMultiTexEnviEXT");
            bindGLFunc(cast(void**)&glMultiTexEnvivEXT, "glMultiTexEnvivEXT");
            bindGLFunc(cast(void**)&glMultiTexGendEXT, "glMultiTexGendEXT");
            bindGLFunc(cast(void**)&glMultiTexGendvEXT, "glMultiTexGendvEXT");
            bindGLFunc(cast(void**)&glMultiTexGenfEXT, "glMultiTexGenfEXT");
            bindGLFunc(cast(void**)&glMultiTexGenfvEXT, "glMultiTexGenfvEXT");
            bindGLFunc(cast(void**)&glMultiTexGeniEXT, "glMultiTexGeniEXT");
            bindGLFunc(cast(void**)&glMultiTexGenivEXT, "glMultiTexGenivEXT");
            bindGLFunc(cast(void**)&glGetMultiTexEnvfvEXT, "glGetMultiTexEnvfvEXT");
            bindGLFunc(cast(void**)&glGetMultiTexEnvivEXT, "glGetMultiTexEnvivEXT");
            bindGLFunc(cast(void**)&glGetMultiTexGendvEXT, "glGetMultiTexGendvEXT");
            bindGLFunc(cast(void**)&glGetMultiTexGenfvEXT, "glGetMultiTexGenfvEXT");
            bindGLFunc(cast(void**)&glGetMultiTexGenivEXT, "glGetMultiTexGenivEXT");
            bindGLFunc(cast(void**)&glMultiTexParameteriEXT, "glMultiTexParameteriEXT");
            bindGLFunc(cast(void**)&glMultiTexParameterivEXT, "glMultiTexParameterivEXT");
            bindGLFunc(cast(void**)&glMultiTexParameterfEXT, "glMultiTexParameterfEXT");
            bindGLFunc(cast(void**)&glMultiTexParameterfvEXT, "glMultiTexParameterfvEXT");
            bindGLFunc(cast(void**)&glMultiTexImage1DEXT, "glMultiTexImage1DEXT");
            bindGLFunc(cast(void**)&glMultiTexImage2DEXT, "glMultiTexImage2DEXT");
            bindGLFunc(cast(void**)&glMultiTexSubImage1DEXT, "glMultiTexSubImage1DEXT");
            bindGLFunc(cast(void**)&glMultiTexSubImage2DEXT, "glMultiTexSubImage2DEXT");
            bindGLFunc(cast(void**)&glCopyMultiTexImage1DEXT, "glCopyMultiTexImage1DEXT");
            bindGLFunc(cast(void**)&glCopyMultiTexImage2DEXT, "glCopyMultiTexImage2DEXT");
            bindGLFunc(cast(void**)&glCopyMultiTexSubImage1DEXT, "glCopyMultiTexSubImage1DEXT");
            bindGLFunc(cast(void**)&glCopyMultiTexSubImage2DEXT, "glCopyMultiTexSubImage2DEXT");
            bindGLFunc(cast(void**)&glGetMultiTexImageEXT, "glGetMultiTexImageEXT");
            bindGLFunc(cast(void**)&glGetMultiTexParameterfvEXT, "glGetMultiTexParameterfvEXT");
            bindGLFunc(cast(void**)&glGetMultiTexParameterivEXT, "glGetMultiTexParameterivEXT");
            bindGLFunc(cast(void**)&glGetMultiTexLevelParameterfvEXT, "glGetMultiTexLevelParameterfvEXT");
            bindGLFunc(cast(void**)&glGetMultiTexLevelParameterivEXT, "glGetMultiTexLevelParameterivEXT");
            bindGLFunc(cast(void**)&glMultiTexImage3DEXT, "glMultiTexImage3DEXT");
            bindGLFunc(cast(void**)&glMultiTexSubImage3DEXT, "glMultiTexSubImage3DEXT");
            bindGLFunc(cast(void**)&glCopyMultiTexSubImage3DEXT, "glCopyMultiTexSubImage3DEXT");
            bindGLFunc(cast(void**)&glEnableClientStateIndexedEXT, "glEnableClientStateIndexedEXT");
            bindGLFunc(cast(void**)&glDisableClientStateIndexedEXT, "glDisableClientStateIndexedEXT");
            bindGLFunc(cast(void**)&glGetFloatIndexedvEXT, "glGetFloatIndexedvEXT");
            bindGLFunc(cast(void**)&glGetDoubleIndexedvEXT, "glGetDoubleIndexedvEXT");
            bindGLFunc(cast(void**)&glGetPointerIndexedvEXT, "glGetPointerIndexedvEXT");
        }
        
        if(glversion >= GLVersion.GL13)
        {
            bindGLFunc(cast(void**)&glCompressedTextureImage3DEXT, "glCompressedTextureImage3DEXT");
            bindGLFunc(cast(void**)&glCompressedTextureImage2DEXT, "glCompressedTextureImage2DEXT");
            bindGLFunc(cast(void**)&glCompressedTextureImage1DEXT, "glCompressedTextureImage1DEXT");
            bindGLFunc(cast(void**)&glCompressedTextureSubImage3DEXT, "glCompressedTextureSubImage3DEXT");
            bindGLFunc(cast(void**)&glCompressedTextureSubImage2DEXT, "glCompressedTextureSubImage2DEXT");
            bindGLFunc(cast(void**)&glCompressedTextureSubImage1DEXT, "glCompressedTextureSubImage1DEXT");
            bindGLFunc(cast(void**)&glGetCompressedTextureImageEXT, "glGetCompressedTextureImageEXT");
            bindGLFunc(cast(void**)&glCompressedMultiTexImage3DEXT, "glCompressedMultiTexImage3DEXT");
            bindGLFunc(cast(void**)&glCompressedMultiTexImage2DEXT, "glCompressedMultiTexImage2DEXT");
            bindGLFunc(cast(void**)&glCompressedMultiTexImage1DEXT, "glCompressedMultiTexImage1DEXT");
            bindGLFunc(cast(void**)&glCompressedMultiTexSubImage3DEXT, "glCompressedMultiTexSubImage3DEXT");
            bindGLFunc(cast(void**)&glCompressedMultiTexSubImage2DEXT, "glCompressedMultiTexSubImage2DEXT");
            bindGLFunc(cast(void**)&glCompressedMultiTexSubImage1DEXT, "glCompressedMultiTexSubImage1DEXT");
            bindGLFunc(cast(void**)&glGetCompressedMultiTexImageEXT, "glGetCompressedMultiTexImageEXT");
            bindGLFunc(cast(void**)&glMatrixLoadTransposefEXT, "glMatrixLoadTransposefEXT");
            bindGLFunc(cast(void**)&glMatrixLoadTransposedEXT, "glMatrixLoadTransposedEXT");
            bindGLFunc(cast(void**)&glMatrixMultTransposefEXT, "glMatrixMultTransposefEXT");
            bindGLFunc(cast(void**)&glMatrixMultTransposedEXT, "glMatrixMultTransposedEXT");
        }
        
        if(glversion >= GLVersion.GL15)
        {
            bindGLFunc(cast(void**)&glNamedBufferDataEXT, "glNamedBufferDataEXT");
            bindGLFunc(cast(void**)&glNamedBufferSubDataEXT, "glNamedBufferSubDataEXT");
            bindGLFunc(cast(void**)&glMapNamedBufferEXT, "glMapNamedBufferEXT");
            bindGLFunc(cast(void**)&glUnmapNamedBufferEXT, "glUnmapNamedBufferEXT");
            bindGLFunc(cast(void**)&glGetNamedBufferParameterivEXT, "glGetNamedBufferParameterivEXT");
            bindGLFunc(cast(void**)&glGetNamedBufferPointervEXT, "glGetNamedBufferPointervEXT");
            bindGLFunc(cast(void**)&glGetNamedBufferSubDataEXT, "glGetNamedBufferSubDataEXT");
        }
        
        if(glversion >= GLVersion.GL20)
        {
            bindGLFunc(cast(void**)&glProgramUniform1fEXT, "glProgramUniform1fEXT");
            bindGLFunc(cast(void**)&glProgramUniform2fEXT, "glProgramUniform2fEXT");
            bindGLFunc(cast(void**)&glProgramUniform3fEXT, "glProgramUniform3fEXT");
            bindGLFunc(cast(void**)&glProgramUniform4fEXT, "glProgramUniform4fEXT");
            bindGLFunc(cast(void**)&glProgramUniform1iEXT, "glProgramUniform1iEXT");
            bindGLFunc(cast(void**)&glProgramUniform2iEXT, "glProgramUniform2iEXT");
            bindGLFunc(cast(void**)&glProgramUniform3iEXT, "glProgramUniform3iEXT");
            bindGLFunc(cast(void**)&glProgramUniform4iEXT, "glProgramUniform4iEXT");
            bindGLFunc(cast(void**)&glProgramUniform1fvEXT, "glProgramUniform1fvEXT");
            bindGLFunc(cast(void**)&glProgramUniform2fvEXT, "glProgramUniform2fvEXT");
            bindGLFunc(cast(void**)&glProgramUniform3fvEXT, "glProgramUniform3fvEXT");
            bindGLFunc(cast(void**)&glProgramUniform4fvEXT, "glProgramUniform4fvEXT");
            bindGLFunc(cast(void**)&glProgramUniform1ivEXT, "glProgramUniform1ivEXT");
            bindGLFunc(cast(void**)&glProgramUniform2ivEXT, "glProgramUniform2ivEXT");
            bindGLFunc(cast(void**)&glProgramUniform3ivEXT, "glProgramUniform3ivEXT");
            bindGLFunc(cast(void**)&glProgramUniform4ivEXT, "glProgramUniform4ivEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix2fvEXT, "glProgramUniformMatrix2fvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix3fvEXT, "glProgramUniformMatrix3fvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix4fvEXT, "glProgramUniformMatrix4fvEXT");
        }
        
        if(glversion >= GLVersion.GL21)
        {
            bindGLFunc(cast(void**)&glProgramUniformMatrix2x3fvEXT, "glProgramUniformMatrix2x3fvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix3x2fvEXT, "glProgramUniformMatrix3x2fvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix2x4fvEXT, "glProgramUniformMatrix2x4fvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix4x2fvEXT, "glProgramUniformMatrix4x2fvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix3x4fvEXT, "glProgramUniformMatrix3x4fvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix4x3fvEXT, "glProgramUniformMatrix4x3fvEXT");
        }
        
        if(glversion >= GLVersion.GL30)
        {
            try
            {
                bindGLFunc(cast(void**)&glEnableClientStateiEXT, "glEnableClientStateiEXT");
                bindGLFunc(cast(void**)&glDisableClientStateiEXT, "glDisableClientStateiEXT");
                bindGLFunc(cast(void**)&glGetFloati_vEXT, "glGetFloati_vEXT");
                bindGLFunc(cast(void**)&glGetDoublei_vEXT, "glGetDoublei_vEXT");
                bindGLFunc(cast(void**)&glGetPointeri_vEXT, "glGetPointeri_vEXT");
            } 
            catch(Exception e)
            {
                bindGLFunc(cast(void**)&glEnableClientStateiEXT, "glEnableClientStateIndexedEXT");
                bindGLFunc(cast(void**)&glDisableClientStateiEXT, "glDisableClientStateIndexedEXT");            
                bindGLFunc(cast(void**)&glGetFloati_vEXT, "glGetFloatIndexedvEXT");
                bindGLFunc(cast(void**)&glGetDoublei_vEXT, "glGetDoubleIndexedvEXT");
                bindGLFunc(cast(void**)&glGetPointeri_vEXT, "glGetPointerIndexedvEXT");
            }
            
            bindGLFunc(cast(void**)&glNamedRenderbufferStorageEXT, "glNamedRenderbufferStorageEXT");
            bindGLFunc(cast(void**)&glGetNamedRenderbufferParameterivEXT, "glGetNamedRenderbufferParameterivEXT");
            bindGLFunc(cast(void**)&glNamedRenderbufferStorageMultisampleEXT, "glNamedRenderbufferStorageMultisampleEXT");
            bindGLFunc(cast(void**)&glCheckNamedFramebufferStatusEXT, "glCheckNamedFramebufferStatusEXT");
            bindGLFunc(cast(void**)&glNamedFramebufferTexture1DEXT, "glNamedFramebufferTexture1DEXT");
            bindGLFunc(cast(void**)&glNamedFramebufferTexture2DEXT, "glNamedFramebufferTexture2DEXT");
            bindGLFunc(cast(void**)&glNamedFramebufferTexture3DEXT, "glNamedFramebufferTexture3DEXT");
            bindGLFunc(cast(void**)&glNamedFramebufferRenderbufferEXT, "glNamedFramebufferRenderbufferEXT");
            bindGLFunc(cast(void**)&glGetNamedFramebufferAttachmentParameterivEXT, "glGetNamedFramebufferAttachmentParameterivEXT");
            bindGLFunc(cast(void**)&glGenerateTextureMipmapEXT, "glGenerateTextureMipmapEXT");
            bindGLFunc(cast(void**)&glGenerateMultiTexMipmapEXT, "glGenerateMultiTexMipmapEXT");
            bindGLFunc(cast(void**)&glFramebufferDrawBufferEXT, "glFramebufferDrawBufferEXT");
            bindGLFunc(cast(void**)&glFramebufferDrawBuffersEXT, "glFramebufferDrawBuffersEXT");
            bindGLFunc(cast(void**)&glFramebufferReadBufferEXT, "glFramebufferReadBufferEXT");
            bindGLFunc(cast(void**)&glGetFramebufferParameterivEXT, "glGetFramebufferParameterivEXT");
            bindGLFunc(cast(void**)&glNamedCopyBufferSubDataEXT, "glNamedCopyBufferSubDataEXT");
            bindGLFunc(cast(void**)&glVertexArrayVertexOffsetEXT, "glVertexArrayVertexOffsetEXT");
            bindGLFunc(cast(void**)&glVertexArrayColorOffsetEXT, "glVertexArrayColorOffsetEXT");
            bindGLFunc(cast(void**)&glVertexArrayEdgeFlagOffsetEXT, "glVertexArrayEdgeFlagOffsetEXT");
            bindGLFunc(cast(void**)&glVertexArrayIndexOffsetEXT, "glVertexArrayIndexOffsetEXT");
            bindGLFunc(cast(void**)&glVertexArrayNormalOffsetEXT, "glVertexArrayNormalOffsetEXT");
            bindGLFunc(cast(void**)&glVertexArrayTexCoordOffsetEXT, "glVertexArrayTexCoordOffsetEXT");
            bindGLFunc(cast(void**)&glVertexArrayMultiTexCoordOffsetEXT, "glVertexArrayMultiTexCoordOffsetEXT");
            bindGLFunc(cast(void**)&glVertexArrayFogCoordOffsetEXT, "glVertexArrayFogCoordOffsetEXT");
            bindGLFunc(cast(void**)&glVertexArraySecondaryColorOffsetEXT, "glVertexArraySecondaryColorOffsetEXT");
            bindGLFunc(cast(void**)&glVertexArrayVertexAttribOffsetEXT, "glVertexArrayVertexAttribOffsetEXT");
            bindGLFunc(cast(void**)&glVertexArrayVertexAttribIOffsetEXT, "glVertexArrayVertexAttribIOffsetEXT");
            bindGLFunc(cast(void**)&glEnableVertexArrayEXT, "glEnableVertexArrayEXT");
            bindGLFunc(cast(void**)&glDisableVertexArrayEXT, "glDisableVertexArrayEXT");
            bindGLFunc(cast(void**)&glEnableVertexArrayAttribEXT, "glEnableVertexArrayAttribEXT");
            bindGLFunc(cast(void**)&glDisableVertexArrayAttribEXT, "glDisableVertexArrayAttribEXT");
            bindGLFunc(cast(void**)&glGetVertexArrayIntegervEXT, "glGetVertexArrayIntegervEXT");
            bindGLFunc(cast(void**)&glGetVertexArrayPointervEXT, "glGetVertexArrayPointervEXT");
            bindGLFunc(cast(void**)&glGetVertexArrayIntegeri_vEXT, "glGetVertexArrayIntegeri_vEXT");
            bindGLFunc(cast(void**)&glGetVertexArrayPointeri_vEXT, "glGetVertexArrayPointeri_vEXT");
            bindGLFunc(cast(void**)&glMapNamedBufferRangeEXT, "glMapNamedBufferRangeEXT");
            bindGLFunc(cast(void**)&glFlushMappedNamedBufferRangeEXT, "glFlushMappedNamedBufferRangeEXT");
        }
        
        if (isExtSupported(glversion, "GL_EXT_draw_buffers2"))
        {
            bindGLFunc(cast(void**)&glEnableIndexedEXT, "glEnableIndexedEXT");
            bindGLFunc(cast(void**)&glDisableIndexedEXT, "glDisableIndexedEXT");
            bindGLFunc(cast(void**)&glIsEnabledIndexedEXT, "glIsEnabledIndexedEXT");
            bindGLFunc(cast(void**)&glGetIntegerIndexedvEXT, "glGetIntegerIndexedvEXT");
            bindGLFunc(cast(void**)&glGetBooleanIndexedvEXT, "glGetBooleanIndexedvEXT");
        }
        
        if (isExtSupported(glversion, "GL_ARB_vertex_program"))
        {
            bindGLFunc(cast(void**)&glNamedProgramStringEXT, "glNamedProgramStringEXT");
            bindGLFunc(cast(void**)&glNamedProgramLocalParameter4dEXT, "glNamedProgramLocalParameter4dEXT");
            bindGLFunc(cast(void**)&glNamedProgramLocalParameter4dvEXT, "glNamedProgramLocalParameter4dvEXT");
            bindGLFunc(cast(void**)&glNamedProgramLocalParameter4fEXT, "glNamedProgramLocalParameter4fEXT");
            bindGLFunc(cast(void**)&glNamedProgramLocalParameter4fvEXT, "glNamedProgramLocalParameter4fvEXT");
            bindGLFunc(cast(void**)&glGetNamedProgramLocalParameterdvEXT, "glGetNamedProgramLocalParameterdvEXT");
            bindGLFunc(cast(void**)&glGetNamedProgramLocalParameterfvEXT, "glGetNamedProgramLocalParameterfvEXT");
            bindGLFunc(cast(void**)&glGetNamedProgramivEXT, "glGetNamedProgramivEXT");
            bindGLFunc(cast(void**)&glGetNamedProgramStringEXT, "glGetNamedProgramStringEXT");
        }

        if (isExtSupported(glversion, "GL_EXT_texture_buffer_object"))
        {
            bindGLFunc(cast(void**)&glTextureBufferEXT, "glTextureBufferEXT");
            bindGLFunc(cast(void**)&glMultiTexBufferEXT, "glMultiTexBufferEXT");
        }

        if (isExtSupported(glversion, "GL_EXT_texture_integer"))
        {
            bindGLFunc(cast(void**)&glTextureParameterIivEXT, "glTextureParameterIivEXT");
            bindGLFunc(cast(void**)&glTextureParameterIuivEXT, "glTextureParameterIuivEXT");
            bindGLFunc(cast(void**)&glGetTextureParameterIivEXT, "glGetTextureParameterIivEXT");
            bindGLFunc(cast(void**)&glGetTextureParameterIuivEXT, "glGetTextureParameterIuivEXT");
            bindGLFunc(cast(void**)&glMultiTexParameterIivEXT, "glMultiTexParameterIivEXT");
            bindGLFunc(cast(void**)&glMultiTexParameterIuivEXT, "glMultiTexParameterIuivEXT");
            bindGLFunc(cast(void**)&glGetMultiTexParameterIivEXT, "glGetMultiTexParameterIivEXT");
            bindGLFunc(cast(void**)&glGetMultiTexParameterIuivEXT, "glGetMultiTexParameterIuivEXT");
        }

        if (isExtSupported(glversion, "GL_EXT_gpu_shader4"))
        {
            bindGLFunc(cast(void**)&glProgramUniform1uiEXT, "glProgramUniform1uiEXT");
            bindGLFunc(cast(void**)&glProgramUniform2uiEXT, "glProgramUniform2uiEXT");
            bindGLFunc(cast(void**)&glProgramUniform3uiEXT, "glProgramUniform3uiEXT");
            bindGLFunc(cast(void**)&glProgramUniform4uiEXT, "glProgramUniform4uiEXT");
            bindGLFunc(cast(void**)&glProgramUniform1uivEXT, "glProgramUniform1uivEXT");
            bindGLFunc(cast(void**)&glProgramUniform2uivEXT, "glProgramUniform2uivEXT");
            bindGLFunc(cast(void**)&glProgramUniform3uivEXT, "glProgramUniform3uivEXT");
            bindGLFunc(cast(void**)&glProgramUniform4uivEXT, "glProgramUniform4uivEXT");
        }

        if (isExtSupported(glversion, "GL_EXT_gpu_program_parameters"))
        {
            bindGLFunc(cast(void**)&glNamedProgramLocalParameters4fvEXT, "glNamedProgramLocalParameters4fvEXT");
        }

        if (isExtSupported(glversion, "GL_NV_gpu_program4"))
        {
            bindGLFunc(cast(void**)&glNamedProgramLocalParameterI4iEXT, "glNamedProgramLocalParameterI4iEXT");
            bindGLFunc(cast(void**)&glNamedProgramLocalParameterI4ivEXT, "glNamedProgramLocalParameterI4ivEXT");
            bindGLFunc(cast(void**)&glNamedProgramLocalParametersI4ivEXT, "glNamedProgramLocalParametersI4ivEXT");
            bindGLFunc(cast(void**)&glNamedProgramLocalParameterI4uiEXT, "glNamedProgramLocalParameterI4uiEXT");
            bindGLFunc(cast(void**)&glNamedProgramLocalParameterI4uivEXT, "glNamedProgramLocalParameterI4uivEXT");
            bindGLFunc(cast(void**)&glNamedProgramLocalParametersI4uivEXT, "glNamedProgramLocalParametersI4uivEXT");
            bindGLFunc(cast(void**)&glGetNamedProgramLocalParameterIivEXT, "glGetNamedProgramLocalParameterIivEXT");
            bindGLFunc(cast(void**)&glGetNamedProgramLocalParameterIuivEXT, "glGetNamedProgramLocalParameterIuivEXT");
        }

        if (isExtSupported(glversion, "GL_NV_framebuffer_multisample_coverage"))
        {
            bindGLFunc(cast(void**)&glNamedRenderbufferStorageMultisampleCoverageEXT, "glNamedRenderbufferStorageMultisampleCoverageEXT");
        }

        if (isExtSupported(glversion, "GL_EXT_geometry_shader4") || isExtSupported(glversion, "GL_NV_gpu_program4"))
        {
            bindGLFunc(cast(void**)&glNamedFramebufferTextureEXT, "glNamedFramebufferTextureEXT");
            bindGLFunc(cast(void**)&glNamedFramebufferTextureLayerEXT, "glNamedFramebufferTextureLayerEXT");
            bindGLFunc(cast(void**)&glNamedFramebufferTextureFaceEXT, "glNamedFramebufferTextureFaceEXT");
        }

        if (isExtSupported(glversion, "GL_NV_explicit_multisample"))
        {
            bindGLFunc(cast(void**)&glTextureRenderbufferEXT, "glTextureRenderbufferEXT");
            bindGLFunc(cast(void**)&glMultiTexRenderbufferEXT, "glMultiTexRenderbufferEXT");
        }
        
        if (isExtSupported(glversion, "GL_ARB_gpu_shader_fp64"))
        {
            bindGLFunc(cast(void**)&glProgramUniform1dEXT, "glProgramUniform1dEXT");
            bindGLFunc(cast(void**)&glProgramUniform2dEXT, "glProgramUniform2dEXT");
            bindGLFunc(cast(void**)&glProgramUniform3dEXT, "glProgramUniform3dEXT");
            bindGLFunc(cast(void**)&glProgramUniform4dEXT, "glProgramUniform4dEXT");
            bindGLFunc(cast(void**)&glProgramUniform1dvEXT, "glProgramUniform1dvEXT");
            bindGLFunc(cast(void**)&glProgramUniform2dvEXT, "glProgramUniform2dvEXT");
            bindGLFunc(cast(void**)&glProgramUniform3dvEXT, "glProgramUniform3dvEXT");
            bindGLFunc(cast(void**)&glProgramUniform4dvEXT, "glProgramUniform4dvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix2dvEXT, "glProgramUniformMatrix2dvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix3dvEXT, "glProgramUniformMatrix3dvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix4dvEXT, "glProgramUniformMatrix4dvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix2x3dvEXT, "glProgramUniformMatrix2x3dvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix2x4dvEXT, "glProgramUniformMatrix2x4dvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix3x2dvEXT, "glProgramUniformMatrix3x2dvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix3x4dvEXT, "glProgramUniformMatrix3x4dvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix4x2dvEXT, "glProgramUniformMatrix4x2dvEXT");
            bindGLFunc(cast(void**)&glProgramUniformMatrix4x3dvEXT, "glProgramUniformMatrix4x3dvEXT");
        }
        
        _EXT_direct_state_access = true;
    }
    catch(Exception e)
    {
        _EXT_direct_state_access = false;
    }
}

package void loadEXT(GLVersion glversion)
{
    _EXT_texture_filter_anisotropic = isExtSupported(glversion, "GL_EXT_texture_filter_anisotropic");
    _EXT_framebuffer_object = isExtSupported(glversion, "GL_EXT_framebuffer_object");
    _EXT_direct_state_access = isExtSupported(glversion, "GL_EXT_direct_state_access");
    if(_EXT_framebuffer_object) load_EXT_framebuffer_object();
    if(_EXT_direct_state_access) load_EXT_direct_state_access(glversion);
}
